[package]
name = "kaulan"
version = "0.1.3"
edition = "2021"

[lib]
name = "kaulan"
path = "src/lib.rs"

[[bin]]
name = "kaulan"
path = "src/main.rs"

[dependencies]
actix-web = { workspace = true }
actix-files = "0.6"
actix-multipart = "0.7"
futures = "0.3"
serde = { workspace = true }
actix-cors = "0.7"
sea-orm = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dirs = "5"
base64 = "0.22"
thiserror = "1"
async-trait = "0.1"
bytes = "1"
tokio-util = { version = "0.7", features = ["io"] }
uuid = { version = "1.22.0", features = ["v4", "serde"] }
gethostname = "1.1.0"
tempfile = "3"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "ico"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
ytdl-audio = { path = "../vendor/ytdl-audio" }
download-core = { path = "../vendor/ncmdump-rs/download-core" }
netease-api = { path = "../vendor/ncmdump-rs/netease-api" }
bilibili-api = { path = "../vendor/ncmdump-rs/bilibili-api" }

[target.'cfg(windows)'.dependencies]
rusty_ffmpeg = { path = "../vendor/rusty_ffmpeg", features = ["link_vcpkg_ffmpeg", "ffmpeg8_1"] }

[target.'cfg(not(windows))'.dependencies]
rusty_ffmpeg = { path = "../vendor/rusty_ffmpeg", features = ["link_system_ffmpeg", "ffmpeg8_1"] }
